### PR TITLE
Documentation done for introduction,colors,typo

### PR DESCRIPTION
**Pull request by animeshgarai09**

### CODE REVIEW

**Comment by manojsarna** [comment]
1. Home page , make it responsive ( hint use z-index)

2. Navigation Links Color can be improved. See the Contrasy Ratio for them. 

3.  If you are using <code> tag in your text use it correctly. Make it visible and vibrant. ( !important CSS :P ) 

4. font weight can be look up to for the text of the website.

5. Improve icons ( what is that ??? ) please change

6. Improve upon Badge designs.

**Review by vrx29 — APPROVED** [review]
Looks good to me. There is a typo in buttons page you have put warning button text as primary check that

**Comment by animeshgarai09** [comment]
> Looks good to me. There is a typo in buttons page you have put warning button text as primary check that

Thanks. will change it

**Comment by sainath7878** [comment]
LGTM

**Pull request merged**
